language: ruby
notifications:
  email: false
  hipchat:
    rooms:
      secure: dUIlXtegER2Pz/71SQ6D6htahaXlKgtqxeNz3SjjzmJREvUfKjD/8knP6tV9w05ks5DH+B31YDMgpP1GH1nFZ7EHKjDcx+FAV9QrBd5PEca3su0O+5QJQp0sIXuBw72TDeWQrr4d9Lp9yHB1Tlc5oI5gNVswmAUTbKLmDBxhgAc=
    template:
      - 'Hubot Packages updated! Restarting Hubot'
      - '@vertica ping'
